version: '3'
services:
  gateway:
    build:
      context: .
      dockerfile: ./images/Dockerfile.nginx
      args:
        package_path: "./packages/gateway"
    image: gateway
    container_name: gateway
    ports:
      - "3000:80"
    entrypoint: ["nginx", "-g", "daemon off;"]

  graphql:
    build:
      context: .
      dockerfile: ./images/Dockerfile.node.dev
    container_name: dev.graphql
    environment:
      NODE_ENV: "development"
      PACKAGE_PATH: "/code/packages/graphql"
    volumes:
      - ./packages:/code/packages

    ports:
      - "3102:3000"
      - "5860:5858"
    entrypoint: ["yarn", "debug:ts"]

  client:
    build:
      context: .
      dockerfile: ./images/Dockerfile.node.dev
    container_name: client
    environment:
      NODE_ENV: "development"
      PACKAGE_PATH: "/code/packages/client"
    volumes:
      - ./packages:/code/packages

    ports:
      - "3103:3000"
      - "5861:5858"
    entrypoint: ['yarn', 'debug:client']

  users-service:
    build:
      context: .
      dockerfile: ./images/Dockerfile.node.dev
    container_name: users-service
    environment:
      NODE_ENV: "development"
      PACKAGE_PATH: "/code/packages/users-service"
    volumes:
      - ./packages:/code/packages

    ports:
      - "3104:3000"
      - "5862:5858"
    entrypoint: ["yarn", "debug:ts"]
