version: '3'
services:
  package_one:
    build:
      context: .
      dockerfile: df.dev
    image: deb:dev
    container_name: dev.package-one
    environment:
      NODE_ENV: "development"
      PACKAGE_PATH: "/code/packages/package-one"
    volumes:
      - ./packages:/code/packages
    ports:
      - "3100:3000"
      - "5858:5858"
    entrypoint: ["yarn", "debug"]
  package_two:
    build:
      context: .
      dockerfile: df.dev
    image: deb:dev
    container_name: dev.package-two
    environment:
      NODE_ENV: "development"
      PACKAGE_PATH: "/code/packages/package-two"
    volumes:
      - ./packages:/code/packages

    ports:
      - "3101:3000"
      - "5859:5858"
    entrypoint: ["yarn", "debug"]