apiVersion: v1
kind: Service
metadata:
  name: application
  labels:
    run: application
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    run: application
