kind: PersistentVolume
apiVersion: v1
metadata:
  name: workspace-volume
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/code"

