apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: users-service-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: users-service
    spec:
      volumes:
      - name: code
        hostPath:
          path: /Users/chris/Sites/docker-yarn-workspace-demo
      containers:
      - name: users-service
        image: node:next
        env:
        - name: PACKAGE_PATH
          value: /code/packages/users-service
        command:
        - yarn
        - debug:ts
        ports:
        - containerPort: 5858
        - containerPort: 3000
        volumeMounts:
        - name: code
          mountPath: /code
---
apiVersion: v1
kind: Service
metadata:
name: users-service-svc
labels:
  run: application
spec:
  selector:
    run: users-service
  type: NodePort
  ports:
  - name: debug-port
    port: 5858
    targetPort: 5858
    nodePort: 32002
  - name: http
    port: 80
    targetPort: 3000
    
